spring.application.name=suma-adugai-backend
# Database connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/suma_adugai?useSSL=false&serverTimezone=UTC
spring.datasource.username=suma_adugai_admin
spring.datasource.password=varun003

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Show SQL Queries (optional)
spring.jpa.show-sql=true

# Logging settings
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Disable JTA platform (if not using JTA transactions)
spring.jpa.properties.hibernate.transaction.jta.platform=none

# Disable open-in-view to avoid database queries during view rendering
spring.jpa.open-in-view=false


